### ISSUE TITLE
keep vpnadmin accessible thought https://ipadress/vpnadmin ?

### ISSUE THREAD

**Issue by datatierce** [YunoHost-Apps/vpnclient_ynh#58]
By default, after the installation, it's only under https://domain/vpnadmin that we can configure the things.

It is possible to keep it accessible under https://eth.ip/vpnadmin or https://wifi.ip/vpnadmin ?

**Comment by pitchum** [comment]
Unfortunately it's not possible AFAIK.
That's because the vpnclient is a yunohost app and apps are only reachable by their respective domain names, not by IP addresses (otherwise an auto-redirection occur).

A good solution would be to move all this config pages into the yunohost admin Web interface, that can be reach by IP address if needed.

There where plans to do so lately but no one could start working on it so far.
Maybe @HugoPoi will try something in that direction soon. At least I hope so :)

**Comment by pitchum** [comment]
Work in progress in #65

**Comment by alexAubin** [comment]
Wontfix
